# fly.toml app configuration file generated for snapshot-front-bold-snowflake-2945 on 2025-02-05T14:21:41+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'snapshot-front-bold-snowflake-2945'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
